### ISSUE TITLE
Can't upload files larger than 2GB

### ISSUE THREAD

**Issue by k0ylass** [MVKozlov/GMGoogleDrive#1]
This is the error thrown when uploading files over 2GB:

Set-GDriveItemContent : System.Management.Automation.MethodException: Cannot convert argument "val2", with value: "7325106436", for "Min" to type "System.Int32": "Cannot convert value "7325106436" to type "System.Int32". Error: "Value was either too large or too 
small for an Int32."" ---> System.Management.Automation.PSInvalidCastException: Cannot convert value "7325106436" to type "System.Int32". Error: "Value was either too large or too small for an Int32." ---> System.OverflowException: Value was either too large or too 
small for an Int32.
   at System.Convert.ToInt32(Int64 value)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Management.Automation.LanguagePrimitives.ConvertNumeric(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   --- End of inner exception stack trace ---
   at System.Management.Automation.LanguagePrimitives.ConvertNumeric(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at CallSite.Target(Closure , CallSite , Type , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Set-GDriveItemContent(Closure , FunctionContext )
At C:\windows\system32\windowspowershell\v1.0\Modules\GMGoogleDrive-master\GMGoogleDrive\Public\Add-GDriveItem.ps1:97 char:5
+     Set-GDriveItemContent @PSBoundParameters
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-GDriveItemContent

**Comment by MVKozlov** [comment]
Thanks for your feedback. Please test latest commit
