### ISSUE TITLE
Set-GDriveItemContent - "name" parameter value cannot be null

### ISSUE THREAD

**Issue by andrewmetcalfbede** [MVKozlov/GMGoogleDrive#17]
Receiving the following error when using the `Set-GDriveItemContent` cmdlet when attempting to update an existing file, similarly getting the same error when using `Add-GDriveItem` which uses it as well when attempting to create a new file.

```
PS C:\users\test\Desktop> echo $file.FullName
C:\users\test\Desktop\Documents\test.rtsz

PS C:\users\test\Desktop> echo $idValue
1Q1v-SXVaz0s0v6UOmVqhEjcmnuj1gEJm

PS C:\users\test\Desktop> Set-GDriveItemContent -AccessToken $accessToken -InFile $file.FullName -ID $idValue -Verbose
VERBOSE: Updating File 1Q1v-SXVaz0s0v6UOmVqhEjcmnuj1gEJm
VERBOSE: URI: https://www.googleapis.com/upload/drive/v3/files/1Q1v-SXVaz0s0v6UOmVqhEjcmnuj1gEJm?supportsAllDrives=true&uploadType=r
esumable&fields=kind,id,name,mimeType,parents
VERBOSE: Metadata upload, resumable, 37193 bytes, application/octet-stream
VERBOSE: Performing the operation "Uploading file from [C:\users\test\Desktop\Documents\test.rtsz]" on target "1Q1v-SX
Vaz0s0v6UOmVqhEjcmnuj1gEJm".
VERBOSE: PATCH https://www.googleapis.com/upload/drive/v3/files/1Q1v-SXVaz0s0v6UOmVqhEjcmnuj1gEJm?supportsAllDrives=true&uploadType=
resumable&fields=kind,id,name,mimeType,parents with -1-byte payload
VERBOSE: received 0-byte response of content type text/plain; charset=utf-8,application/json; charset=UTF-8

Set-GDriveItemContent : System.ArgumentNullException: Value cannot be null.
Parameter name: name
   at System.Globalization.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at Microsoft.PowerShell.Commands.ContentHelper.GetEncodingOrDefault(String characterSet)
   at Microsoft.PowerShell.Commands.BasicHtmlWebResponseObject.InitializeContent()
   at Microsoft.PowerShell.Commands.WebResponseObjectFactory.GetResponseObject(WebResponse response, Stream responseStream, 
ExecutionContext executionContext, Boolean useBasicParsing)
   at Microsoft.PowerShell.Commands.InvokeWebRequestCommand.ProcessResponse(WebResponse response)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
At line:1 char:1
+ Set-GDriveItemContent -AccessToken $accessToken -InFile $file.FullNam ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-GDriveItemContent
```

**Comment by MVKozlov** [comment]
Sorry cannot repeat this error.
You use personal drive or team drive ? I never test it on team drive because I haven't access to it
Latest module version ?

Your  item `1Q1v-SXVaz0s0v6UOmVqhEjcmnuj1gEJm` have name on google drive ?

because error not inside cmdlet itself, but deep in dotnet code, I can't determine where is error
You may add some debugging to `Set-GDriveItemContent.ps1` to help me with this error
something like 'write-host 1'. 'write-host 2' after every line starting 199 and to 218
``` powershell
        try {
            if ($PSCmdlet.ShouldProcess($ID, $uploadString)) {
                write-host 1
                $wr = Invoke-WebRequest @WebRequestParams @GDriveProxySettings
                write-host 2
            }
        }
        catch {
            write-host 3
            $UploadResult.Error = $_.Exception
            write-host 4
            $UploadResult
            Write-Error $_.Exception
            return
        }

        if ($PSVersionTable.PSVersion.Major -ge 7) {
            $WebRequestParams.SkipHttpErrorCheck = $true # allow to work with 308 "error" code in PSv7
        }
        write-host 5
        $WebRequestParams.ContentType = $ContentType
        write-host 6
        if ($wr.StatusCode -in 200,308) {
            write-host 7
            $UploadResult.ResumeID = $wr.Headers['X-GUploader-UploadID'] | Select-Object -First 1
            write-host 8
            Write-Verbose "ResumeID: $($UploadResult.ResumeID)"
            write-host 9
```

this way we can find exactly line which generate this error

**Comment by andrewmetcalfbede** [comment]
Thanks for the reply!  

Yes this folder is part of our enterprise account, it has worked until recently.  We're using the most recent module version (cloned from Github from default branch each time we run our script).

Yes the file has a name in Google Drive, or rather it did have a name until I deleted it because I wanted to see if it was just an issue with updating an existing file or creating a new one, this was before I realised that the `Add-GDriveItem` uses `Set-GDriveItemContent`.  I've created a new folder in-case there was some issue with the folder and opened it up to public access but still getting the same.  Here's a snippet of our script and the variable values as well as the result of a new attempt with the `Write-Host`s added.

```
foreach ($file in Get-ChildItem .\Documents -File) {
  try {
    $searchResult = Find-GDriveItem -AccessToken $accessToken -Query "name = '$($File.Name)' and '$GDriveFolderID' in parents and trashed = false" -Property id
    if ($searchResult.files) {
      Write-Output "$($File.Name) exists, updating..."
      $idValue = $searchResult.files | Select-Object -ExpandProperty id
      Set-GDriveItemContent -AccessToken $accessToken -InFile $file.FullName -ID $idValue -Verbose
    } 
    else {
      Write-Output "Uploading $($File.Name)"
      Add-GDriveItem -AccessToken $accessToken -InFile $file.FullName -Name "$file.Name" -ParentID $GDriveFolderID -Verbose
    }
  }
  catch {
    Write-Output "Error uploading $($File.Name)"
  }
}
```

```
PS C:\test> echo $file


    Directory: C:\test\Documents


Mode                LastWriteTime         Length Name                                                                                               
----                -------------         ------ ----                                                                                               
-a----        8/22/2023   1:03 PM          37169 SOP_PR01.rtsz

PS C:\test> echo $GDriveFolderID
129b-7zO5f9pqKszDm8M9K6HhbFgUHs1X

PS C:\test> echo $file.FullName
C:\test\Documents\SOP_PR01.rtsz

PS C:\test> echo $file.Name
SOP_PR01.rtsz

```

![image](https://github.com/MVKozlov/GMGoogleDrive/assets/42937783/9529d891-f0a1-460c-805d-a4747a32d13c)


```
Uploading SOP_PR01.rtsz
VERBOSE: Constructed Metadata: { "name": "SOP_PR01.rtsz.Name", "parents": ["129b-7zO5f9pqKszDm8M9K6HhbFgUHs1X"] }
VERBOSE: Creating New file
VERBOSE: URI: https://www.googleapis.com/upload/drive/v3/files/?supportsAllDrives=true&uploadType=resumable&fields=kind,id,name,mimeType,parents
VERBOSE: Metadata upload, resumable, 37169 bytes, application/octet-stream
VERBOSE: Performing the operation "Uploading file named 'SOP_PR01.rtsz.Name' from [C:\test\Documents\SOP_PR01.rtsz]" on target "".
1
VERBOSE: POST https://www.googleapis.com/upload/drive/v3/files/?supportsAllDrives=true&uploadType=resumable&fields=kind,id,name,mimeType,parents with
 -1-byte payload
VERBOSE: received 0-byte response of content type text/plain; charset=utf-8,application/json; charset=UTF-8
3
4

Item     : 
ResumeID : 
Error    : System.ArgumentNullException: Value cannot be null.
           Parameter name: name
              at System.Globalization.EncodingTable.GetCodePageFromName(String name)
              at System.Text.Encoding.GetEncoding(String name)
              at Microsoft.PowerShell.Commands.ContentHelper.GetEncodingOrDefault(String characterSet)
              at Microsoft.PowerShell.Commands.BasicHtmlWebResponseObject.InitializeContent()
              at Microsoft.PowerShell.Commands.WebResponseObjectFactory.GetResponseObject(WebResponse response, Stream responseStream, 
           ExecutionContext executionContext, Boolean useBasicParsing)
              at Microsoft.PowerShell.Commands.InvokeWebRequestCommand.ProcessResponse(WebResponse response)
              at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
              at System.Management.Automation.CommandProcessor.ProcessRecord()

Error uploading SOP_PR01.rtsz
```

```
PS C:\test> $PSVersionTable

Name                           Value                                                                                                                
----                           -----                                                                                                                
PSVersion                      5.1.14409.1005                                                                                                       
PSEdition                      Desktop                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                              
BuildVersion                   10.0.14409.1005                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                      
WSManStackVersion              3.0                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                  
SerializationVersion           1.1.0.1      
```

**Comment by MVKozlov** [comment]
so we get an exception right inside
`$wr = Invoke-WebRequest @WebRequestParams @GDriveProxySettings`
As far as I can see you are using psv5.1 on Windows 7.
Can you test it on other machine ? may be on Windows 10/PSv5.1 or Windows7/PSv7?

according to the Exception, something wrong on your system
the .Net code
```
    at System.Globalization.EncodingTable.GetCodePageFromName(String name)
    at System.Text.Encoding.GetEncoding(String name)
    at Microsoft.PowerShell.Commands.ContentHelper.GetEncodingOrDefault(String characterSet)
```
looks like

``` c#
internal static Encoding GetEncodingOrDefault(string characterSet)
    {
      string name = string.IsNullOrEmpty(characterSet) ? "ISO-8859-1" : characterSet;
      try
      {
        return Encoding.GetEncoding(name);
      }
      catch (ArgumentException ex)
      {
        return Encoding.GetEncoding(0);
      }
    }
...
public static Encoding GetEncoding(string name)
    {
      return EncodingProvider.GetEncodingFromProvider(name) ?? Encoding.GetEncoding(EncodingTable.GetCodePageFromName(name));
    }
...
internal static Encoding GetEncodingFromProvider(string encodingName)
    {
      if (EncodingProvider.s_providers == null)
        return (Encoding) null;
      foreach (EncodingProvider encodingProvider in EncodingProvider.s_providers)
      {
        Encoding encoding = encodingProvider.GetEncoding(encodingName);
        if (encoding != null)
          return encoding;
      }
      return (Encoding) null;
    }
```
because of `string name = string.IsNullOrEmpty(characterSet) ? "ISO-8859-1" : characterSet;`
**name** cannot be **null**

so **null** will be set if `GetEncodingFromProvider` return **null**
and my system on non-existent encoding return other exception
``` powershell
PS C:\Windows\system32> [System.Text.Encoding]::GetEncoding('asd')
Exception calling "GetEncoding" with "1" argument(s): "'asd' is not a supported encoding name. For information on defin
ing a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
```
so I think you system encoding provider list may be damaged

**Comment by andrewmetcalfbede** [comment]
Thanks very much for your help on this, seems like it is something we will need to work out on our end.  I'll close this off but I will let you know if we manage to work around it, else we will just need to migrate the workflow to a newer machine / Powershell version.
